package netutil

import "testing"

func TestParseVersionINI(t *testing.T) {
	content := `# Linux-BBR-v3 version info (auto-generated by CI)
[cli]
commit=14635050
built=2026-08-25T13:06:56Z

[kernel]
version=7.2.0
`
	ini, err := ParseVersionINI(content)
	if err != nil {
		t.Fatalf("ParseVersionINI: %v", err)
	}
	if ini.CLICommit != "14635050" {
		t.Errorf("CLICommit = %q, want 14635050", ini.CLICommit)
	}
	if ini.CLIBuilt != "2026-08-25T13:06:56Z" {
		t.Errorf("CLIBuilt = %q", ini.CLIBuilt)
	}
	if ini.KernelVersion != "7.2.0" {
		t.Errorf("KernelVersion = %q, want 7.2.0", ini.KernelVersion)
	}

	// 空内容报错
	if _, err := ParseVersionINI("# only comment\n"); err == nil {
		t.Error("空内容应报错")
	}
	// 未知键/节容忍
	ini2, err := ParseVersionINI("[cli]\ncommit=abc\n[unknown]\nx=1\n")
	if err != nil || ini2.CLICommit != "abc" {
		t.Errorf("未知节应被容忍: %v %+v", err, ini2)
	}
}
